const ADD_DATA="ADD_DATA";
const DEL_DATA="DEL_DATA";
const INIT_DATA="INIT_DATA";
const AMTEND_USER="AMTEND_USER";
const ADDUSER_DETAIL="ADDUSER_DETAIL";
const ADD_DETAILlIST="ADD_DETAILlIST";
const ADD_ID="ADD_ID";
const SINGLE_PRICE="SINGLE_PRICE";
const GET_ALL_USER="GET_ALL_USER";
export {
    ADD_DATA,
    DEL_DATA,
    INIT_DATA,
    AMTEND_USER,
    ADDUSER_DETAIL,
    ADD_DETAILlIST,
    ADD_ID,
    SINGLE_PRICE,
    GET_ALL_USER
}